NDF/NDF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls',namespace="main")),
]

NDF/main/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^stud_profile/$', views.stud_profile, name='stud_profile'),
    url(r'^rules/$', views.rules, name='rules'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^stud_full_dept/$', views.stud_full_dept, name='stud_full_dept'),
    url(r'^stud_full_lab/$', views.stud_full_lab, name='stud_full_lab'),
    url(r'^faculty_profile/$', views.faculty_profile, name='faculty_profile'),
    url(r'^library_profile/$', views.library_profile, name='library_profile'),
    url(r'^caretaker_profile/$', views.caretaker_profile, name='caretaker_profile'),
    url(r'^gymkhana_profile/$', views.gymkhana_profile, name='gymkhana_profile'),
    url(r'^assireg_profile/$', views.assireg_profile, name='assireg_profile'),
    url(r'^warden_profile/$', views.warden_profile, name='warden_profile'),
    url(r'^onlinecc_profile/$', views.onlinecc_profile, name='onlinecc_profile'),
    url(r'^cc_profile/$', views.cc_profile, name='cc_profile'),
    url(r'^thesis_manager_profile/$', views.thesis_manager_profile, name='thesis_manager_profile'),
    url(r'^lab_profile/$', views.lab_profile, name='lab_profile'),
    url(r'^hod_profile/$', views.hod_profile, name='hod_profile'),
    url(r'^account_profile/$', views.account_profile, name='account_profile'),


]

    #url(r'stud_profile/1$', views.stud_profile, names='stud_profile'),
    #url(r'^stud_profile/(?P<username>\w+)/', views.stud_profile, name='stud_overall'),
    #url(r'^stud_profile/(.*)/dept$', views.stud_full_dept, name='stud_dept'),
    #url(r'^stud_profile/(.*)/lab$',views.stud_full_lab , name='stud_lab'),


#index is view name

NDF/main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ['name', 'webmail', 'department', 'hostel']


class FacultyForm(forms.ModelForm):

    class Meta:
        model = Faculty
        fields = ['webmail', 'department','name']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

NDF/main/views.py
from django.http import HttpResponse
from django.template import loader
from .models import *
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect,reverse, HttpResponseRedirect
from django.db.models import Q
from .forms import UserForm

'''def index(request):
    return HttpResponse("<h1>This is index app homepage</h1>")'''



def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        role = request.POST['role']
        print role
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                #print 'stud1'
                login(request, user)
                #print role+'1'
                role = str(role)
                #print type(Student.webmail)
                if role == "Student":
                    return redirect('/stud_profile')
                elif role == "Faculty":
                    return redirect('/faculty_profile')
                elif role == "Lab":
                    return redirect('/lab_profile')
                elif role == "Caretaker":
                    return redirect('/caretaker_profile')
                elif role == "Warden":
                    return redirect('/warden_profile')
                elif role == "Gymkhana":
                    return redirect('/gymkhana_profile')
                elif role == "OnlineCC":
                    return redirect('/onlinecc_profile')
                elif role == "CC":
                    return redirect('/cc_profile')
                elif role == "Thesis Manager":
                    return redirect('/thesis_manager_profile')
                elif role == "Library":
                    return redirect('/library_profile')
                elif role == "Assistant Registrar":
                    return redirect('/assireg_profile')
                elif role == "HOD":
                    return redirect('/hod_profile')
                elif role == "Account":
                    return redirect('/account_profile')
                elif role == "Admin":
                    return redirect('/admin')
                else:
                    return render(request, 'main/login.html', {'error_message': 'Unsuccessful Login'})
            else:
                return render(request, 'main/login.html', {'error_message': 'Session Expired'})
        else:
            return render(request, 'main/login.html', {'error_message': 'Credentials Invalid'})
    return render(request, 'main/login.html',{'error_message': ''})

def stud_profile(request):
    username=request.user.username
    try:
        student = Student.objects.get(webmail=username)
    except Student.DoesNotExist:
        student = None
    if student is None:
        return render(request, 'main/login.html', {'error_message': 'Role mismatch'})
    student = Student.objects.get(webmail=username)
    return render(request, 'main/stud.html', {'error_message': 'valid login', 'student': student})

def rules(request):
    username=request.user.username
    try:
        student = Student.objects.get(webmail=username)
    except Student.DoesNotExist:
        student = None
    return render(request,'main/rules.html', {'student':student})

def contact(request):
    username = request.user.username
    try:
        student = Student.objects.get(webmail=username)
    except Student.DoesNotExist:
        student = None
    return render(request, 'main/contact.html', {'student': student})

def stud_full_dept(request):
    username = request.user.username
    username=str(username)
    student = Student.objects.get(webmail=username)
    faculty_dept = Faculty.objects.filter(department=student.department)
    stud_fac_status = Stud_Faculty_Status.objects.filter(student=student)
    return render(request, 'main/stud_full_dept.html', {'error_message': 'valid login', 'student': student, 'faculty':faculty_dept,'Stud_Faculty_Status':stud_fac_status})


def stud_full_lab(request):
    username = request.user.username
    username = str(username)
    student = Student.objects.get(webmail=username)
    labs = Lab.objects.all()
    stud_lab_status = Stud_Lab_Status.objects.filter(student=student)
    return render(request, 'main/stud_full_lab.html', {'error_message': 'valid login', 'student': student, 'labs' : labs, 'Stud_Lab_Status':stud_lab_status})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    return render(request, 'main/login.html', {"form": form})

def faculty_profile(request):
    if request.method == "GET":
        username = request.user.username
        try:
            fac = Faculty.objects.get(webmail=username)
        except Faculty.DoesNotExist:
            fac = None
        if fac is None:
            return render(request, 'main/login.html', {'error_message': 'Role mismatch'})
        #fac = Faculty.objects.get(webmail=username)
        dept = fac.department
        students = Student.objects.filter(department=dept)
        stud_fac_status = Stud_Faculty_Status.objects.filter(faculty=fac)
        return render(request, 'main/faculty.html',
                      {'error_message': 'valid login', 'students': students, 'faculty': fac, 'dept': dept,
                       'Stud_Faculty_Status': stud_fac_status})
    elif request.method=="POST":
        username = request.user.username
        fac = Faculty.objects.get(webmail=username)
        dept = fac.department
        students = Student.objects.filter(department=dept)
        stud_fac_status = Stud_Faculty_Status.objects.filter(faculty=fac)
        for stud in students:
            for i in stud_fac_status :
                if i.student.webmail == stud.webmail:
                    remarks = request.POST[str(stud.roll_no)]
                    print type(remarks)
                    print remarks
                    if request.POST.get(stud.webmail,"") == 'on':
                        x=Stud_Faculty_Status.objects.get(student=stud, faculty=fac)
                        x.faculty_approval=True
                        x.faculty_remarks=remarks
                        x.save()
                        #stud.save()
                        #print Stud_Faculty_Status.objects.get(student=stud, faculty=fac).faculty_approval
                    else :
                        x = Stud_Faculty_Status.objects.get(student=stud, faculty=fac)
                        print x
                        x.faculty_approval=False
                        stud.HOD_approval=False
                        stud.account_approval=False
                        x.faculty_remarks = remarks
                        stud.save()
                        x.save()
                        #print Stud_Faculty_Status.objects.get(student=stud, faculty=fac).faculty_approval
        return redirect('/faculty_profile')

def lab_profile(request):
    if request.method == "GET":
        username = request.user.username
        try:
            lab = Lab.objects.get(webmail=username)
        except Lab.DoesNotExist:
            lab = None
        if lab is None:
            return render(request, 'main/login.html', {'error_message': 'Role mismatch'})
        #lab = Lab.objects.get(webmail=username)
        students = Student.objects.all()
        stud_lab_status = Stud_Lab_Status.objects.filter(lab=lab)
        return render(request, 'main/lab.html',
                      {'error_message': 'valid login', 'students': students, 'lab': lab, 'Stud_Lab_Status': stud_lab_status})
    elif request.method=="POST":
        username = request.user.username
        lab = Lab.objects.get(webmail=username)
        students = Student.objects.all()
        stud_lab_status = Stud_Lab_Status.objects.filter(lab=lab)
        for stud in students:
            for i in stud_lab_status :
                if i.student.webmail == stud.webmail:
                    if request.POST.get(stud.webmail,"") == 'on':
                        x=Stud_Lab_Status.objects.get(student=stud, lab=lab)
                        x.lab_approval=True
                        x.save()
                        #stud.save()
                        #print Stud_Faculty_Status.objects.get(student=stud, faculty=fac).faculty_approval
                    else :
                        x = Stud_Lab_Status.objects.get(student=stud, lab=lab)
                        print x.student
                        x.lab_approval=False
                        stud.HOD_approval=False
                        stud.account_approval=False
                        stud.save()
                        x.save()

                        #print Stud_Faculty_Status.objects.get(student=stud, faculty=fac).faculty_approval
        return redirect('/lab_profile')

def caretaker_profile(request):
    if request.method == "GET":
        username = request.user.username
        try:
            caretaker = Caretaker.objects.get(webmail=username)
        except Caretaker.DoesNotExist:
            caretaker = None
        if caretaker is None:
            return render(request, 'main/login.html', {'error_message': 'Role mismatch'})
        #caretaker = Caretaker.objects.get(webmail=username)
        hostel = caretaker.hostel
        students = Student.objects.filter(hostel=hostel)
        return render(request, 'main/caretaker.html',
                      {'error_message': 'valid login', 'students': students, 'caretaker': caretaker, 'hostel': hostel})
    elif request.method=="POST":
        username = request.user.username
        caretaker = Caretaker.objects.get(webmail=username)
        hostel = caretaker.hostel
        students = Student.objects.filter(hostel=hostel)
        for stud in students:
            if request.POST.get(stud.webmail,"") == 'on':
                stud.caretaker_approval=True

NDF/main/templates/main/account.html
{% extends 'main/base.html' %}

{% block title %}
    {{ account.name }}|Home Page
{% endblock %}

{% block heading %}
    Students{% endblock %}

{% block form-action %}
    {% url 'main:account_profile'%}
{% endblock %}

{% block NotApproved %}
      {%for stud in students %}
          {% if stud.account_approval is False %}
                         <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="{{ stud.webmail }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.name }}</p>
          {% endif %}
      {% endfor %}
{% endblock %}
{% block Approved %}
      {%for stud in students %}
          {% if stud.account_approval is True %}
                         <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" checked name="{{ stud.webmail }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.name }}</p>
          {% endif %}
      {% endfor %}
{% endblock %}

NDF/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Faculty Catalog{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
        function checkAll(bx){
            var form = bx.form;
            var ischecked = bx.checked;
            for (var i = 0; i < form.length; ++i) {
                if (form[i].type == 'checkbox') {
                    form[i].checked = ischecked;
                }
    }

}</script>

  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}

    /* Set gray background color and 100% height */

    .check-right {
      padding-top: 20px;
      background-color: #b3ffb3;
      height: 100%;
    }
    .check-left {
      padding-top: 20px;
      background-color:  #ffcccc;
      height: 100%;
    }
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
        padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
   .row.content {height:auto;}
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Welcome!</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'main:logout_user' %}">Logout <span class="glyphicon glyphicon-log-out"></span> </a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">
  <div class="row content">
  <div class="well">
        <h2>{% block heading %}Students{% endblock %}</h2>
  </div>
  <form class="form-horizontal" role="form" action="{% block form-action %}{% url 'main:faculty_profile'%}{% endblock %}" method="post" enctype="multipart/form-data">

	  {% csrf_token %}
	  <div class="col-sm-6 text-center">
	      <h4>Not Approved</h4>
	      <hr>
	      <div class = "check-left">
          <p align="left">
                        <div class="col-sm-4 text-left" >&nbsp;<input type="checkbox" onclick="checkAll(this)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Select All</div>
                        <br>
          </p>
{% block NotApproved %}

{% endblock %}

	      </div>

	  </div>
	    <div class="col-sm-6 text-center">
	      <h4>Approved</h4>

	      <hr>
	        <div class = "check-right">
            {% comment %}<p align="left">
                        <div class="col-sm-4 text-left" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" onclick="checkAll(this)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Unselect All</div>
                        <br>
          </p>{% endcomment %}
{% block Approved %}
{% endblock %}
            </div>
	      </div>

	  </div>
	  <div class="col-sm-12">
	        <button type="submit" onclick="return confirm('Are you sure?')" class="btn btn-success">Save changes</button>
	  </div>
  </form>
</div>


<footer class="container-fluid text-center">
  <p>&copy; 2016 IIT Guwahati</p>
</footer>

</body>
</html>

NDF/main/templates/main/caretaker.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

NDF/main/templates/main/cc.html
{% extends 'main/base.html' %}

{% block title %}
    {{ cc.name }} Incharge |Home Page
{% endblock %}

{% block heading %}
    Students with No Online CC Dues
{% endblock %}

{% block form-action %}
    {% url 'main:cc_profile'%}
{% endblock %}

{% block NotApproved %}
      {%for stud in students %}
          {% if stud.CC_approval is False %}
                         <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name="{{ stud.webmail }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.name }}</p>
          {% endif %}
      {% endfor %}
{% endblock %}
{% block Approved %}
      {%for stud in students %}
          {% if stud.CC_approval is True %}
                         <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" checked name="{{ stud.webmail }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.name }}</p>
          {% endif %}
      {% endfor %}
{% endblock %}

NDF/main/templates/main/faculty.html
{#{% extends 'main/base.html' %}#}
{#{% block title %}{% endblock %}#}
{#% block heading %}{% endblock %}#}
{#{% block form-action %}{% endblock %}#}
{#{% block NotApproved %}{% endblock %}#}
{#{% block Approved %} {% endblock %}#}


{% extends 'main/base.html' %}

{% block title %}
    {{ faculty.name }}|Home Page
{% endblock %}

{% block heading %}
    Students of {{ faculty.department }}
{% endblock %}

{% block form-action %}
    {% url 'main:faculty_profile'%}
{% endblock %}

{% block NotApproved %}
    {%for stud in students %}
          {% for i in Stud_Faculty_Status %}
               {% if i.student.name == stud.name %}
                    {% if i.faculty_approval is False %}

                        <p align="left">
                        <div class="col-sm-4 text-center" style="font-size: 14px;"><input type="checkbox" name="{{ stud.webmail }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.name }}</div>
                        <div class="col-sm-8 text-center"><input id="{{ stud.roll_no }}" maxlength="250" class="form-control" style="width:300px;height: 28px;" name="{{ stud.roll_no }}" type="text" value="{{ i.faculty_remarks }}"></div>
                        <br>

                        </p>
                    {%endif%}
                {% endif %}
           {% endfor %}
      {% endfor %}
{% endblock %}
{% block Approved %}
    {%for stud in students %}
          {% for i in Stud_Faculty_Status %}
               {% if i.student.name == stud.name %}
                    {% if i.faculty_approval is True %}
                        <p align="left">
                        <div class="col-sm-4 text-center" style="font-size: 14px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" checked name="{{ stud.webmail }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ stud.name }}</div>
                        <div class="col-sm-8 text-center"><input id="{{ stud.roll_no }}" maxlength="250" class="form-control" style="width:300px;height: 28px;" name="{{ stud.roll_no }}" type="text" value="{{ i.faculty_remarks }}"></div>
                        <br>
                        </p>
                    {%endif%}
               {% endif %}
          {% endfor %}
    {% endfor %}
{% endblock %}

NDF/main/templates/main/rules.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Rules{{ student.name }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>
<body>
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav hidden-xs">
      <h4>Welcome {{ student.name }}!</h4>
    <ul class="nav nav-pills nav-stacked">
        <li><a href="{% url 'main:stud_profile' %}">Overall status</a></li>
        <li><a class="active" href="{% url 'main:stud_full_dept' %}">Department detailed status</a></li>
        <li><a href="{% url 'main:stud_full_lab' %}"> Lab detailed status</a></li>
        <li><a href="{% url 'main:rules' %}">Rules</a></li>
        <li><a href="{% url 'main:contact' %}">Contact</a></li>
          <li><a href="{% url 'main:logout_user' %}">Log out</a></li>
      </ul><br>
    </div>
    <br>
    <div class="col-sm-9">
      <div class="well">
        <h4>Rules :</h4>
            <p>Write rules here </p>
      </div>
    </div>

    </div>
  </div>

<div id="wrapper">
		<div id="header"></div>
		<div id="content"></div>
		<div id="footer"></div>
	</div>
<footer class="container-fluid text-center">
  <p>&copy; 2016 IIT Guwahati</p>
</footer>

</body>
</html>

NDF/main/templates/main/stud_full_dept.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Department Detail of{{ student.name }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>
<body>
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav hidden-xs">
      <h4>Welcome {{ student.name }}!</h4>
    <ul class="nav nav-pills nav-stacked">
        <li><a href="{% url 'main:stud_profile' %}">Overall status</a></li>
        <li><a class="active" href="{% url 'main:stud_full_dept' %}">Department detailed status</a></li>
        <li><a href="{% url 'main:stud_full_lab' %}"> Lab detailed status</a></li>
        <li><a href="{% url 'main:rules' %}">Rules</a></li>
        <li><a href="{% url 'main:contact' %}">Contact</a></li>
        <li><a href="{% url 'main:logout_user' %}">Log out</a></li>
      </ul><br>
    </div>
    <br>
    <div class="col-sm-9">
      <div class="well">
        <h4>Details :</h4>
            <p>
                <div class="col-sm-4"><b>Faculty : Status</b>
                </div>
                <div class="col-sm-7"><b>
                Remarks</b>
                </div>
                <br>
            </p>

        {%for i in Stud_Faculty_Status %}
            {% if i.faculty.department == i.student.department %}
            <p>
                <div class="col-sm-4">{{ i.faculty.name }} :
                {% if i.faculty_approval is True %}
                    <span style="color: #11B54A">Approved</span>
                {%else%}
                    <span style="color:#e92916">Not Approved</span>
                    {% endif %}
                </div>
                <div class="col-sm-7">
                {% if i.faculty_approval is True %}
                    {{ i.faculty_remarks }}
                {%else%}
                    {{ i.faculty_remarks }}
                {% endif %}
                </div>
                <br>
            </p>
            {% endif %}
          {% endfor %}
      </div>
    </div>

    </div>
  </div>

<div id="wrapper">
		<div id="header"></div>
		<div id="content"></div>
		<div id="footer"></div>
	</div>
<footer class="container-fluid text-center">
  <p>&copy; 2016 IIT Guwahati</p>
</footer>

</body>
</html>


NDF/main/templates/main/stud_full_lab.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Lab Detail of {{ student.name }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>
<body>
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav hidden-xs">
      <h4>Welcome {{ student.name }}!</h4>
      <ul class="nav nav-pills nav-stacked">
        <li><a href="{% url 'main:stud_profile' %}">Overall status</a></li>
        <li><a href="{% url 'main:stud_full_dept' %}"> Department detailed status</a></li>
          <li><a class="active">Lab detailed status</a></li>
          <li><a href="#">Rules</a></li>
          <li><a href="#">Chart/About</a></li>
          <li><a href="{% url 'main:logout_user' %}">Log out</a></li>
      </ul><br>
    </div>
    <br>
    <div class="col-sm-9">
      <div class="well">
        <h4>Details :</h4>
           {%for i in Stud_Lab_Status %}
            <p>
                {{ i.lab.name }} :
                {% if i.lab_approval is True %}
                    Approved
                {%else%}
                    Not Approved
                {% endif %}
            </p>
          {% endfor %}
      </div>
    </div>

    </div>
  </div>

<div id="wrapper">
		<div id="header"></div>
		<div id="content"></div>
		<div id="footer"></div>
	</div>
<footer class="container-fluid text-center">
  <p>&copy; 2016 IIT Guwahati</p>
</footer>

</body>
</html>
